name: Build and Push Docker Image on New Tag

on:
  push:
    tags:
      - 'v*'  # 匹配以 'v' 开头的 tag，例如 v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry registry.cn-hangzhou.aliyuncs.com
          uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
          with:
            registry: registry.cn-hangzhou.aliyuncs.com
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: extract_tag
        run: |
          TAG_NAME=$(echo ${{ github.ref }} | sed -e 's,refs/tags/,,')
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REPOSITORY }}:${{ env.TAG_NAME }}